### ISSUE TITLE
Cheat doesnt work for me on the latest patch

### ISSUE THREAD

**Issue by tiesdf** [CheaterRehab/GodFather-Fortnite-Cheat-Cracked#1]
gui is showing aswell as the crosshair and radar but its not showing the players on the radar, nor is the esp or aimbot working

**Comment by ItsRauss** [comment]
> gui is showing aswell as the crosshair and radar but its not showing the players on the radar, nor is the esp or aimbot working

check if uworld updated if its not updated update it and if its still not working thats means you dont load the driver correctly

**Comment by tiesdf** [comment]
i already checked uworld and i could not find where you defined uworld. i checked main.cpp. should it be in there?

**Comment by ItsRauss** [comment]
there is no uworld in this source you should add it yourself

пн, 3 янв. 2022 г. в 23:25, tiesdf ***@***.***>:
